### ISSUE TITLE
What do I need to put in your_linkedin_cookies?

### ISSUE THREAD

**Issue by Bishwas-py** [tamboto2000/golinkedin#4]
I am confused that what really does `your_linkedin_cookies` mean? Is it the `li_at` value?

**Comment by tamboto2000** [comment]
Should be the whole cookie, have you tried it?

**Comment by Bishwas-py** [comment]
> Should be the whole cookie, have you tried it?

Any idea, how to get it?

**Comment by bipin0x01** [comment]
If you're still confused @Bishwas-py , which I don't think as it has been quite long. You can get the cookies from the browser console by running 
console.log(document.cookie);
when logged in.
